//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::categories::Entity as Categories;
pub use super::expense::Entity as Expense;
pub use super::lists::Entity as Lists;
pub use super::movie_lists::Entity as MovieLists;
pub use super::movies::Entity as Movies;
pub use super::users::Entity as Users;
