//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub username: String,
    pub email: Option<String>,
    pub password_hash: String,
    pub password_salt: String,
    pub created_at: Option<DateTimeUtc>,
    pub token: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::expense::Entity")]
    Expense,
    #[sea_orm(has_many = "super::lists::Entity")]
    Lists,
    #[sea_orm(has_many = "super::movies::Entity")]
    Movies,
}

impl Related<super::expense::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Expense.def()
    }
}

impl Related<super::lists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lists.def()
    }
}

impl Related<super::movies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Movies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
